name: 'Star Count'
description: 'Get count of repository stars'
author: 'alteredorange'
inputs:
  repoPath:
    description: 'Repository Path'
    required: false
    default: ${{github.repository}}
outputs:
  stars:
    description: "Repo Stars"
    value: ${{ steps.repo-stars.outputs.stars }}
runs:
  using: composite
  steps:
    - id: repo-stars
      run: |
        STARS=`curl -s 'https://api.github.com/repos/${{ inputs.repoPath }}?page=$i&per_page=100' | jq .stargazers_count`
        echo "::set-output name=stars::$STARS"
      shell: bash
branding:
  icon: 'award'
  color: 'green'
