name: Find Repo Stars and Update README
on:
  push:
    branches:
      - main

jobs:
  find-repo-stars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find repo URLs and stars
        id: repo-stars
        run: |
          REPO_URLS=$(grep -Eo '(?<=https://github.com/)[^ )]+' README.md)
          echo "$REPO_URLS"
          IFS=$'\n'
          for URL in $REPO_URLS; do
            API_URL="https://api.github.com/repos/${URL}?page=$i&per_page=100"
            STAR_COUNT=$(curl -s "$API_URL" | jq '.stargazers_count')
            sed -i "s|$URL|[$URL]($URL) $STAR_COUNT stars|" README.md
          done
