on:
  # Triggers the workflow on push or pull request events but only for the master branch
  watch:
    action: started

steps:
- name: Star Count
  id: repo-stars
  uses: alanhg/repo-star-count-action@master
